[build]
  command = "npm run build"
  publish = "dist"

 codex/fix-netlify-deployment-to-use-custom-domain
[context.production.environment]
  FRONTEND_ENDPOINT = "http://biowell.ai/api/frontend/supplements/update"

# Optional: Configure environment variables for Netlify
#[context.production.environment]
#  NODE_VERSION = "18"
 main
